% Generating Fig.8 from 2410.18186
% (dNeff vs. f/C for tau and muon scatterings) 

% Import the dNeff data for muons
dNeff_data_mu = importdata('dNeff_fa_mu_scat.dat',',',1);
fa_x_mu = dNeff_data_mu.data(:,1);
dNeff_GG_y_mu = dNeff_data_mu.data(:,2); % dNeff from nBE
dNeff_full_y_mu = dNeff_data_mu.data(:,3); % dNeff from fBE


figure1=figure();
axes1 = axes('Parent',figure1);
semilogx(fa_x_mu,dNeff_full_y_mu,'LineWidth',2); 
hold on;
plot(fa_x_mu,dNeff_GG_y_mu,'LineWidth',2);
yline(0.3,'--','LineWidth',2,'Color',[0.7176 0.2745 1.0]); % Planck
yline(0.1,'--','LineWidth',2,'Color',[0.929 0.694 0.125]); % Simons obs.
yline(0.054,'--','LineWidth',2,'Color',[0.466 0.674 0.188]); % CMB-S4
grid on;
xlabel('f_a/C_{\mu} [{\rm GeV}]','Interpreter','tex');
ylabel('\Delta N_{\rm eff}','Interpreter','tex')
set(axes1,'FontSize',25,'XMinorTick','on','XScale','log','YMinorTick','on',...
    'YScale','linear');
% Create textboxes
annotation(figure1,'textbox',...
    [0.780,0.620,0.250,0.057],...
    'Color',[0.7176 0.2745 1.0],...
    'String','Planck (2σ)',...
    'FontSize',25,...
    'FitBoxToText','off',...
    'EdgeColor','none');
annotation(figure1,'textbox',...
    [0.154,0.289,0.352,0.057],...
    'Color',[0.929 0.694 0.125],...
    'String','Simons Obs. (2σ)',...
    'FontSize',25,...
    'FitBoxToText','off',...
    'EdgeColor','none');
annotation(figure1,'textbox',...
    [0.154,0.207,0.348,0.057],...
    'Color',[0.466 0.674 0.188],...
    'String','CMB-S4 (2σ)',...
    'FontSize',25,...
    'FitBoxToText','off',...
    'EdgeColor','none');
hold off;



%% Import the dNeff data for tau
dNeff_data_tau = importdata('dNeff_fa_tau_scat.dat',',',1);
fa_x_tau = dNeff_data_tau.data(:,1);
dNeff_GG_y_tau = dNeff_data_tau.data(:,2); % dNeff from nBE
dNeff_full_y_tau = dNeff_data_tau.data(:,3); % dNeff from fBE


figure2=figure();
axes2 = axes('Parent',figure2);
semilogx(fa_x_tau,dNeff_full_y_tau,'LineWidth',2); 
hold on;
plot(fa_x_tau,dNeff_GG_y_tau,'LineWidth',2);
yline(0.054,'--','LineWidth',2,'Color',[0.466 0.674 0.188]); % CMB-S4
grid on;
xlabel('f_a/C_{\tau} [{\rm GeV}]','Interpreter','tex');
ylabel('\Delta N_{\rm eff}','Interpreter','tex')
set(axes2,'FontSize',25,'XMinorTick','on','XScale','log','YMinorTick','on',...
    'YScale','linear');
% Create textboxes
annotation(figure2,'textbox',...
    [0.705,0.676,0.132,0.057],...
    'Color',[0.466 0.674 0.188],...
    'String','CMB-S4 (2σ)',...
    'FontSize',25,...
    'FitBoxToText','off',...
    'EdgeColor','none');
hold off;

